import { execFile, spawn } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';
import { atomicWriteMany, exists, sha256, stringifyMarkdown, readMarkdown } from './files.js';
import { readProject, readProviderConfig, scanTasks } from './project.js';
import { evidenceRecords, readState } from './task.js';

const exec=promisify(execFile);
const gateConfigSchema=z.object({schema_version:z.literal(1),gates:z.array(z.object({id:z.string().regex(/^[a-z][a-z0-9-]*$/),command:z.array(z.string()).min(1),timeout_seconds:z.number().int().positive()}).strict())}).strict();
const manifestSchema=z.object({schema_version:z.literal(1),task_id:z.string(),repository:z.string(),worktree:z.string(),branch:z.string(),base_commit:z.string(),head:z.string(),created_at:z.iso.datetime()}).strict();
export type WorkspaceManifest=z.infer<typeof manifestSchema>;
const control=(root:string)=>path.join(root,'.spec-loop');

async function git(cwd:string,args:string[]){return (await exec('git',args,{cwd,maxBuffer:10_000_000})).stdout.trim()}
export async function initGateConfig(root:string):Promise<void>{const file=path.join(control(root),'GATES.md');if(await exists(file))return;await atomicWriteMany(root,[{file,content:stringifyMarkdown({schema_version:1,gates:[]},'# Gates\n\nAdd deterministic command arrays before Harness execution.')}])}
export async function readGates(root:string){await initGateConfig(root);return gateConfigSchema.parse((await readMarkdown(path.join(control(root),'GATES.md'))).data).gates}

export async function createWorkspace(root:string,taskId:string):Promise<WorkspaceManifest>{const project=await readProject(root);const task=(await scanTasks(root)).find(t=>t.task_id===taskId);if(!task)throw new Error('task not found');const repo=project.repository;await git(repo,['rev-parse','--is-inside-work-tree']);const base=await git(repo,['rev-parse','HEAD']);const branch=`spec-loop/${taskId.toLowerCase()}`;const wt=path.join(control(root),'worktrees',taskId.toLowerCase());await mkdir(path.dirname(wt),{recursive:true});if(await exists(wt))throw new Error('worktree already exists');await git(repo,['worktree','add','-b',branch,wt,base]);const m={schema_version:1 as const,task_id:taskId,repository:repo,worktree:wt,branch,base_commit:base,head:base,created_at:new Date().toISOString()};manifestSchema.parse(m);await atomicWriteMany(root,[{file:path.join(control(root),'output',`${taskId}-workspace.json`),content:JSON.stringify(m,null,2)+'\n'}]);return m}
export async function readWorkspace(root:string,taskId:string):Promise<WorkspaceManifest>{return manifestSchema.parse(JSON.parse(await readFile(path.join(control(root),'output',`${taskId}-workspace.json`),'utf8')))}

export interface GateResult{id:string;command:string[];exit_code:number;duration_ms:number;head:string;artifact:string;sha256:string}
function assertGateCommand(command:string[]){const joined=command.join(' ').toLowerCase();if(command[0]==='sudo'||(command[0]==='git'&&['push','merge'].includes(command[1]??''))||/\b(deploy|publish|release)\b/.test(joined))throw new Error(`forbidden gate command: ${command.join(' ')}`)}
export async function runGates(root:string,taskId:string):Promise<GateResult[]>{const m=await readWorkspace(root,taskId);const gates=await readGates(root);if(!gates.length)throw new Error('no gates configured');const results:GateResult[]=[];for(const gate of gates){assertGateCommand(gate.command);const start=Date.now();const result=await runProcess(gate.command[0],gate.command.slice(1),m.worktree,gate.timeout_seconds*1000);const head=await git(m.worktree,['rev-parse','HEAD']);const content=`COMMAND ${JSON.stringify(gate.command)}\nEXIT ${result.code}\n\nSTDOUT\n${result.stdout}\nSTDERR\n${result.stderr}\n`;const rel=`.spec-loop/output/${taskId}-gate-${gate.id}.txt`;await atomicWriteMany(root,[{file:path.join(root,rel),content}]);results.push({id:gate.id,command:gate.command,exit_code:result.code,duration_ms:Date.now()-start,head,artifact:rel,sha256:sha256(content)})}await atomicWriteMany(root,[{file:path.join(control(root),'output',`${taskId}-gates.json`),content:JSON.stringify(results,null,2)+'\n'}]);return results}

function runProcess(bin:string,args:string[],cwd:string,timeout:number,input?:string):Promise<{code:number;stdout:string;stderr:string}>{return new Promise((resolve,reject)=>{const child=spawn(bin,args,{cwd,env:{PATH:process.env.PATH??'',HOME:process.env.HOME??'',TMPDIR:process.env.TMPDIR??'/tmp'},stdio:'pipe'});let stdout='',stderr='';const timer=setTimeout(()=>{child.kill('SIGTERM')},timeout);child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);child.on('error',reject);child.on('close',code=>{clearTimeout(timer);resolve({code:code??1,stdout,stderr})});if(input)child.stdin.end(input);else child.stdin.end()})}

export async function prepareHarness(root:string,taskId:string,prompt:string):Promise<string>{const m=await readWorkspace(root,taskId);const task=(await scanTasks(root)).find(t=>t.task_id===taskId);if(!task)throw new Error('task not found');const state=await readState(task.path);const payload={task_id:taskId,round:state.current_round,state:state.status,base_commit:m.base_commit,worktree:m.worktree,prompt,prepared_at:new Date().toISOString()};const file=path.join(control(root),'output',`${taskId}-prepare.json`);await atomicWriteMany(root,[{file,content:JSON.stringify(payload,null,2)+'\n'}]);return file}
export async function executeHarness(root:string,taskId:string,prompt:string):Promise<{code:number;artifact:string}>{const m=await readWorkspace(root,taskId);const cfg=await readProviderConfig(root);const p=cfg.providers[cfg.active_provider];let args=[...p.args];if(cfg.active_provider==='codex')args=['-C',m.worktree,...args,prompt];else args=[...args,prompt];const result=await runProcess(p.executable,args,m.worktree,p.timeout_seconds*1000);const content=`PROVIDER ${cfg.active_provider}\nEXIT ${result.code}\n\nSTDOUT\n${result.stdout}\nSTDERR\n${result.stderr}`;const rel=`.spec-loop/output/${taskId}-provider.txt`;await atomicWriteMany(root,[{file:path.join(root,rel),content}]);return{code:result.code,artifact:rel}}
export async function collectHarness(root:string,taskId:string){const m=await readWorkspace(root,taskId);const head=await git(m.worktree,['rev-parse','HEAD']);const status=await git(m.worktree,['status','--short']);const diff=await git(m.worktree,['diff','--stat',m.base_commit]);const value={task_id:taskId,base_commit:m.base_commit,head,status:status.split('\n').filter(Boolean),diff_stat:diff,collected_at:new Date().toISOString()};await atomicWriteMany(root,[{file:path.join(control(root),'output',`${taskId}-collect.json`),content:JSON.stringify(value,null,2)+'\n'}]);return value}
export async function reportHarness(root:string,taskId:string){const collected=JSON.parse(await readFile(path.join(control(root),'output',`${taskId}-collect.json`),'utf8'));const gates=JSON.parse(await readFile(path.join(control(root),'output',`${taskId}-gates.json`),'utf8')) as GateResult[];const passed=gates.every(g=>g.exit_code===0);const content=`# Harness Report — ${taskId}\n\n- Base: ${collected.base_commit}\n- Head: ${collected.head}\n- Gate verdict: ${passed?'PASS':'FAIL'}\n- Modified entries: ${collected.status.length}\n\n## Gates\n${gates.map(g=>`- ${g.id}: exit ${g.exit_code}, artifact ${g.artifact}`).join('\n')}\n`;const file=path.join(control(root),'output',`${taskId}-harness-report.md`);await atomicWriteMany(root,[{file,content}]);return{passed,file}}

export async function writebackDelivery(root:string,taskId:string){const item=(await scanTasks(root)).find(t=>t.task_id===taskId);if(!item)throw new Error('task not found');const state=await readState(item.path);if(state.status!=='delivered')throw new Error('task is not delivered');const evidence=await evidenceRecords(item.path);const content=`# Project Write-back — ${taskId}\n\n- Project: ${(await readProject(root)).project_id}\n- Status: delivered\n- Round: ${state.current_round}\n- Revision: ${state.code_revision}\n- Evidence: ${evidence.map(e=>e.id).join(', ')}\n\nThis is a generated external-system write-back draft. No external write was performed.\n`;const file=path.join(control(root),'output',`${taskId}-writeback.md`);await atomicWriteMany(root,[{file,content}]);return file}
