import { randomUUID } from 'node:crypto';
import { lstat, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { z } from 'zod';
import { atomicWriteMany, exists, sha256 } from './files.js';
import { buildAcceptanceSchedule, cancelAcceptanceRun, readAcceptanceRun, reconcileCandidateBaseline } from './acceptance-loop.js';
import { cancelRoleInvocation, ingestSucceededRoleResult, latestRoleInvocation, prepareRoleInvocation, readRoleInvocation, reconcileRoleInvocation, runRoleInvocation } from './role-orchestrator.js';
import { readProject, scanTasks } from './project.js';
import { readWorkspace } from './execution.js';
import { cancelTask } from './task.js';
import { cancelTaskExecution } from './execution-events.js';
import { processMatches, processStartedAt, terminateProcessTree } from './process-control.js';

const controlStateSchema=z.object({schema_version:z.literal(1),paused:z.boolean(),killed:z.boolean(),reconcile_required:z.boolean(),updated_at:z.iso.datetime()}).strict();
const leaseStatusSchema=z.enum(['active','released','expired','killed']);
const projectLeaseSchema=z.object({schema_version:z.literal(1),kind:z.literal('project'),lease_id:z.string(),project_id:z.string(),owner:z.string().min(2),owner_nonce:z.string().uuid(),idempotency_key:z.string().min(3),fencing_token:z.number().int().positive(),status:leaseStatusSchema,issued_at:z.iso.datetime(),expires_at:z.iso.datetime(),updated_at:z.iso.datetime()}).strict();
const taskLeaseSchema=z.object({schema_version:z.literal(1),kind:z.literal('task'),lease_id:z.string(),project_lease_id:z.string(),project_fencing_token:z.number().int().positive(),task_id:z.string(),owner:z.string().min(2),owner_nonce:z.string().uuid(),idempotency_key:z.string().min(3),fencing_token:z.number().int().positive(),resources:z.array(z.string()).min(1),action:z.enum(['start_m','start_v','start_r','run_gate']),status:leaseStatusSchema,issued_at:z.iso.datetime(),expires_at:z.iso.datetime(),updated_at:z.iso.datetime()}).strict();
const counterSchema=z.object({schema_version:z.literal(1),next_fencing_token:z.number().int().positive()}).strict();
const waveBudgetSchema=z.object({schema_version:z.literal(1),max_parallel:z.number().int().min(1).max(16),max_elapsed_seconds:z.number().int().min(1).max(3600),max_tokens:z.number().int().positive(),max_cost_usd:z.number().positive(),updated_at:z.iso.datetime()}).strict();
export type ProjectLease=z.infer<typeof projectLeaseSchema>;export type TaskLease=z.infer<typeof taskLeaseSchema>;

const rootDir=(root:string)=>path.join(root,'.spec-loop','scheduler'),stateFile=(root:string)=>path.join(rootDir(root),'CONTROL.json'),counterFile=(root:string)=>path.join(rootDir(root),'COUNTER.json'),budgetFile=(root:string)=>path.join(rootDir(root),'BUDGET.json'),waveDir=(root:string)=>path.join(rootDir(root),'wave-runs');
const projectDir=(root:string)=>path.join(rootDir(root),'project-leases'),taskDir=(root:string)=>path.join(rootDir(root),'task-leases');
const denied=new Set(['merge','push','deploy','credential','credential_write','production_data','external_side_effect','delete','release','publish']);
const exec=promisify(execFile);

export async function initSchedulerControl(root:string){await mkdir(projectDir(root),{recursive:true});await mkdir(taskDir(root),{recursive:true});await mkdir(waveDir(root),{recursive:true});if(!(await exists(stateFile(root))))await atomicWriteMany(root,[{file:stateFile(root),content:`${JSON.stringify({schema_version:1,paused:false,killed:false,reconcile_required:false,updated_at:new Date().toISOString()},null,2)}\n`}]);if(!(await exists(counterFile(root))))await atomicWriteMany(root,[{file:counterFile(root),content:`${JSON.stringify({schema_version:1,next_fencing_token:1},null,2)}\n`}]);if(!(await exists(budgetFile(root))))await atomicWriteMany(root,[{file:budgetFile(root),content:`${JSON.stringify({schema_version:1,max_parallel:2,max_elapsed_seconds:1200,max_tokens:250_000,max_cost_usd:10,updated_at:new Date().toISOString()},null,2)}\n`}]);return controlStateSchema.parse(JSON.parse(await readFile(stateFile(root),'utf8')))}
export async function readWaveBudget(root:string){await initSchedulerControl(root);return waveBudgetSchema.parse(JSON.parse(await readFile(budgetFile(root),'utf8')))}
export async function configureWaveBudget(root:string,input:{maxParallel:number;maxElapsedSeconds:number;maxTokens:number;maxCostUsd:number}){await initSchedulerControl(root);const value=waveBudgetSchema.parse({schema_version:1,max_parallel:input.maxParallel,max_elapsed_seconds:input.maxElapsedSeconds,max_tokens:input.maxTokens,max_cost_usd:input.maxCostUsd,updated_at:new Date().toISOString()});await atomicWriteMany(root,[{file:budgetFile(root),content:`${JSON.stringify(value,null,2)}\n`}]);return value}
async function lock<T>(root:string,operation:()=>Promise<T>):Promise<T>{const mutex=path.join(rootDir(root),'mutex');await mkdir(rootDir(root),{recursive:true});for(let attempt=0;attempt<200;attempt++){try{await mkdir(mutex);await writeFile(path.join(mutex,'owner.json'),`${JSON.stringify({pid:process.pid,at:new Date().toISOString()})}\n`,{flag:'wx'});try{return await operation()}finally{await rm(mutex,{recursive:true,force:true})}}catch(error){if((error as NodeJS.ErrnoException).code!=='EEXIST')throw error;const owner=await readFile(path.join(mutex,'owner.json'),'utf8').then(raw=>JSON.parse(raw)).catch(()=>null);let dead=false;if(owner?.pid)try{process.kill(owner.pid,0)}catch{dead=true}if(dead){await rm(mutex,{recursive:true,force:true});continue}await new Promise(resolve=>setTimeout(resolve,10))}}throw new Error('scheduler control is busy')}
async function state(root:string){await initSchedulerControl(root);return controlStateSchema.parse(JSON.parse(await readFile(stateFile(root),'utf8')))}
async function writeState(root:string,value:z.infer<typeof controlStateSchema>){await atomicWriteMany(root,[{file:stateFile(root),content:`${JSON.stringify(controlStateSchema.parse(value),null,2)}\n`}])}
async function nextToken(root:string){const value=counterSchema.parse(JSON.parse(await readFile(counterFile(root),'utf8'))),token=value.next_fencing_token;await atomicWriteMany(root,[{file:counterFile(root),content:`${JSON.stringify({schema_version:1,next_fencing_token:token+1},null,2)}\n`}]);return token}
async function listLeases<T>(dir:string,schema:z.ZodType<T>):Promise<T[]>{if(!(await exists(dir)))return[];const result=[] as T[];for(const name of (await readdir(dir)).filter(name=>name.endsWith('.json')).sort())result.push(schema.parse(JSON.parse(await readFile(path.join(dir,name),'utf8'))));return result}
function active<T extends {status:z.infer<typeof leaseStatusSchema>;expires_at:string}>(lease:T){return lease.status==='active'&&Date.parse(lease.expires_at)>Date.now()}
async function writeProjectLease(root:string,value:ProjectLease){await atomicWriteMany(root,[{file:path.join(projectDir(root),`${value.lease_id}.json`),content:`${JSON.stringify(projectLeaseSchema.parse(value),null,2)}\n`}])}
async function writeTaskLease(root:string,value:TaskLease){await atomicWriteMany(root,[{file:path.join(taskDir(root),`${value.lease_id}.json`),content:`${JSON.stringify(taskLeaseSchema.parse(value),null,2)}\n`}])}
function ttl(value:number){if(!Number.isInteger(value)||value<1||value>3600)throw new Error('lease ttl must be 1–3600 seconds');return value}
function normalizeResources(values:string[]){const result=[...new Set(values.map(value=>value.trim()))].sort();if(!result.length||result.some(value=>!/^(?:repo|branch|module|tool):[A-Za-z0-9_./-]+$/.test(value)||value.includes('..')))throw new Error('resource claims must use safe repo:/branch:/module:/tool: identifiers');return result}

export async function acquireProjectLease(root:string,input:{owner:string;idempotencyKey:string;ttlSeconds:number}):Promise<ProjectLease>{await initSchedulerControl(root);return lock(root,async()=>{const currentState=await state(root);if(currentState.paused||currentState.killed||currentState.reconcile_required)throw new Error('scheduler is paused, killed, or requires reconcile');const leases=await listLeases(projectDir(root),projectLeaseSchema),same=leases.find(item=>active(item)&&item.idempotency_key===input.idempotencyKey&&item.owner===input.owner);if(same)return same;if(leases.some(active))throw new Error('Project already has an active scheduler lease');const now=new Date(),token=await nextToken(root),value=projectLeaseSchema.parse({schema_version:1,kind:'project',lease_id:`PL-${randomUUID()}`,project_id:(await readProject(root)).project_id,owner:input.owner,owner_nonce:randomUUID(),idempotency_key:input.idempotencyKey,fencing_token:token,status:'active',issued_at:now.toISOString(),expires_at:new Date(now.getTime()+ttl(input.ttlSeconds)*1000).toISOString(),updated_at:now.toISOString()});await writeProjectLease(root,value);return value})}

async function requireProjectLease(root:string,id:string,token:number){const lease=projectLeaseSchema.parse(JSON.parse(await readFile(path.join(projectDir(root),`${id}.json`),'utf8')));if(!active(lease)||lease.fencing_token!==token)throw new Error('stale or inactive Project lease fencing token');return lease}
function resourcesConflict(left:string[],right:string[]){return left.some(resource=>right.includes(resource))}

export async function acquireTaskLease(root:string,input:{projectLeaseId:string;projectFencingToken:number;taskId:string;owner:string;idempotencyKey:string;ttlSeconds:number;resources:string[];action:'start_m'|'start_v'|'start_r'|'run_gate'}):Promise<TaskLease>{await initSchedulerControl(root);return lock(root,async()=>{const currentState=await state(root);if(currentState.paused||currentState.killed||currentState.reconcile_required)throw new Error('scheduler is paused, killed, or requires reconcile');await requireProjectLease(root,input.projectLeaseId,input.projectFencingToken);const run=await readAcceptanceRun(root,input.taskId),allowed={start_m:'m_working',start_v:'plan_compiled',start_r:'v_passed',run_gate:'plan_compiled'}[input.action];if(run.stage!==allowed)throw new Error(`${input.action} is not ready from ${run.stage}`);const schedule=await buildAcceptanceSchedule(root),scheduled=schedule.tasks.find(item=>item.task_id===input.taskId);if(scheduled?.blocked_by.length)throw new Error(`${input.taskId} is blocked by ${scheduled.blocked_by.join(', ')}`);const resources=normalizeResources(input.resources),leases=await listLeases(taskDir(root),taskLeaseSchema),same=leases.find(item=>active(item)&&item.idempotency_key===input.idempotencyKey);if(same){if(same.task_id!==input.taskId||same.action!==input.action||JSON.stringify(same.resources)!==JSON.stringify(resources))throw new Error('task lease idempotency key was reused with different facts');return same}if(leases.some(item=>active(item)&&item.task_id===input.taskId))throw new Error('Task already has an active lease');const conflict=leases.find(item=>active(item)&&resourcesConflict(item.resources,resources));if(conflict)throw new Error(`resources conflict with ${conflict.task_id}: ${conflict.resources.filter(item=>resources.includes(item)).join(', ')}`);const now=new Date(),token=await nextToken(root),value=taskLeaseSchema.parse({schema_version:1,kind:'task',lease_id:`TL-${randomUUID()}`,project_lease_id:input.projectLeaseId,project_fencing_token:input.projectFencingToken,task_id:input.taskId,owner:input.owner,owner_nonce:randomUUID(),idempotency_key:input.idempotencyKey,fencing_token:token,resources,action:input.action,status:'active',issued_at:now.toISOString(),expires_at:new Date(now.getTime()+ttl(input.ttlSeconds)*1000).toISOString(),updated_at:now.toISOString()});await writeTaskLease(root,value);return value})}

export async function assertTaskLeaseResult(root:string,leaseId:string,fencingToken:number,invocationId?:string){const lease=taskLeaseSchema.parse(JSON.parse(await readFile(path.join(taskDir(root),`${leaseId}.json`),'utf8'))),currentState=await state(root);if(currentState.killed||currentState.reconcile_required||!active(lease)||lease.fencing_token!==fencingToken)throw new Error('stale, killed, or inactive Task lease fencing token');await requireProjectLease(root,lease.project_lease_id,lease.project_fencing_token);if(invocationId){const invocation=await readRoleInvocation(root,lease.task_id,invocationId);const expected={start_m:'M',start_v:'V',start_r:'R',run_gate:'V'}[lease.action];if(invocation.role!==expected||invocation.status!=='succeeded')throw new Error('lease result is not bound to the expected succeeded role invocation')}return{accepted:true,lease_id:leaseId,fencing_token:fencingToken,fact_hash:sha256(JSON.stringify(lease))}}
export async function releaseTaskLease(root:string,leaseId:string,fencingToken:number){return lock(root,async()=>{const lease=taskLeaseSchema.parse(JSON.parse(await readFile(path.join(taskDir(root),`${leaseId}.json`),'utf8')));if(!active(lease)||lease.fencing_token!==fencingToken)throw new Error('stale or inactive Task lease fencing token');const updated=taskLeaseSchema.parse({...lease,status:'released',updated_at:new Date().toISOString()});await writeTaskLease(root,updated);return updated})}
export async function releaseProjectLease(root:string,leaseId:string,fencingToken:number){return lock(root,async()=>{const lease=projectLeaseSchema.parse(JSON.parse(await readFile(path.join(projectDir(root),`${leaseId}.json`),'utf8')));if(!active(lease)||lease.fencing_token!==fencingToken)throw new Error('stale or inactive Project lease fencing token');const activeTasks=(await listLeases(taskDir(root),taskLeaseSchema)).filter(item=>active(item)&&item.project_lease_id===leaseId);if(activeTasks.length)throw new Error(`Project lease still owns active Task leases: ${activeTasks.map(item=>item.lease_id).join(', ')}`);const updated=projectLeaseSchema.parse({...lease,status:'released',updated_at:new Date().toISOString()});await writeProjectLease(root,updated);return updated})}

export function assertSchedulerAction(action:string){if(denied.has(action.toLowerCase()))throw new Error(`scheduler action is denied: ${action}`);if(!['start_m','start_v','start_r','run_gate'].includes(action))throw new Error(`scheduler action is not allowlisted: ${action}`);return{allowed:true,action}}
export async function pauseSchedulerControl(root:string){const current=await state(root),updated=controlStateSchema.parse({...current,paused:true,updated_at:new Date().toISOString()});await writeState(root,updated);return updated}
export async function resumeSchedulerControl(root:string){const current=await state(root);if(current.killed||current.reconcile_required)throw new Error('scheduler must reconcile after Kill before resume');const updated=controlStateSchema.parse({...current,paused:false,updated_at:new Date().toISOString()});await writeState(root,updated);return updated}

async function roleInvocations(root:string){const output=path.join(root,'.spec-loop','output'),items=[] as Array<{taskId:string;id:string}>;if(!(await exists(output)))return items;for(const entry of await readdir(output,{withFileTypes:true})){const match=entry.isDirectory()&&entry.name.match(/^((?:WEB-)?TASK-[A-Z0-9-]+)-acceptance-v2$/);if(!match)continue;const dir=path.join(output,entry.name,'invocations');if(!(await exists(dir)))continue;for(const invocation of await readdir(dir,{withFileTypes:true}))if(invocation.isDirectory())items.push({taskId:match[1],id:invocation.name})}return items}

async function cancelActiveEffects(root:string,taskId:string):Promise<{cancelled:string[];incomplete:string[]}>{
  const dir=path.join(root,'.spec-loop','active-effects');if(!(await exists(dir)))return{cancelled:[],incomplete:[]};const cancelled:string[]=[],incomplete:string[]=[];
  for(const name of (await readdir(dir)).filter(value=>value.endsWith('.json'))){const file=path.join(dir,name),info=await lstat(file);if(!info.isFile()||info.isSymbolicLink())throw new Error('active Effect marker is invalid');const value=JSON.parse(await readFile(file,'utf8')) as {effect_id?:string;task_id?:string;pid?:number;process_started_at?:string|null};if(value.task_id!==taskId)continue;if(!value.effect_id||!value.pid)throw new Error('active Effect marker has no auditable identity');if(!value.process_started_at){if(await processMatches(value.pid)){incomplete.push(`${value.effect_id}:legacy marker has no process identity`);continue}cancelled.push(value.effect_id);await rm(file,{force:true});continue}const termination=await terminateProcessTree(value.pid,value.process_started_at);if(termination.stopped){cancelled.push(value.effect_id);await rm(file,{force:true})}else incomplete.push(`${value.effect_id}:${termination.reason}`)}return{cancelled:cancelled.sort(),incomplete:incomplete.sort()};
}

async function stopOrReclaimDriverLock(root:string,taskId:string,reason:string,at:Date):Promise<{reclaimed:boolean;stop_requested:boolean;stop_verified:boolean;stop_error:string|null}>{
  const lockDir=path.join(root,'.spec-loop','locks',`workflow-driver-${taskId}.lock`),info=await lstat(lockDir).catch(()=>null);if(!info)return{reclaimed:false,stop_requested:false,stop_verified:true,stop_error:null};
  if(!info.isDirectory()||info.isSymbolicLink())throw new Error('workflow Driver lock is invalid');
  const owner=await readFile(path.join(lockDir,'owner.json'),'utf8').then(raw=>JSON.parse(raw) as {pid?:number;process_started_at?:string|null}).catch(()=>null);
  if(!owner?.pid)throw new Error('workflow Driver lock has no auditable owner; manual reconcile is required');
  const alive=await processMatches(owner.pid,owner.process_started_at);
  if(alive){const request=path.join(lockDir,'STOP_REQUEST.json'),existing=await lstat(request).catch(()=>null);if(!existing)await atomicWriteMany(root,[{file:request,content:`${JSON.stringify({schema_version:1,task_id:taskId,pid:owner.pid,process_started_at:owner.process_started_at??null,requested_at:at.toISOString(),reason},null,2)}\n`}]);else if(!existing.isFile()||existing.isSymbolicLink())throw new Error('workflow Driver stop request marker is invalid');if(!owner.process_started_at)return{reclaimed:false,stop_requested:true,stop_verified:false,stop_error:'legacy Driver lock has no process identity'};const termination=await terminateProcessTree(owner.pid,owner.process_started_at);if(termination.stopped){await rm(lockDir,{recursive:true,force:true});return{reclaimed:true,stop_requested:true,stop_verified:true,stop_error:null}}return{reclaimed:false,stop_requested:true,stop_verified:false,stop_error:termination.reason}}
  await rm(lockDir,{recursive:true,force:true});return{reclaimed:true,stop_requested:false,stop_verified:true,stop_error:null};
}

export async function stopTaskExecution(root:string,taskId:string,reason='stopped by user'){
  const marker=path.join(root,'.spec-loop','output',`${taskId}-stop.json`);
  if(await exists(marker)){
    const previous=JSON.parse(await readFile(marker,'utf8')) as Record<string,unknown>,driver=await stopOrReclaimDriverLock(root,taskId,String(previous.reason??reason),new Date()),effects=await cancelActiveEffects(root,taskId);
    const incomplete=[...effects.incomplete,...(driver.stop_verified?[]:[`driver:${driver.stop_error??'not verified'}`])],updated={...previous,cancelled_effects:[...new Set([...(Array.isArray(previous.cancelled_effects)?previous.cancelled_effects:[]),...effects.cancelled])].sort(),incomplete_stops:incomplete,stop_complete:incomplete.length===0,driver_lock_reclaimed:Boolean(previous.driver_lock_reclaimed)||driver.reclaimed,driver_stop_requested:driver.stop_requested,driver_stop_verified:driver.stop_verified,driver_stop_error:driver.stop_error};
    if(JSON.stringify(updated)!==JSON.stringify(previous))await atomicWriteMany(root,[{file:marker,content:`${JSON.stringify(updated,null,2)}\n`}]);
    return updated;
  }
  const task=(await scanTasks(root)).find(item=>item.task_id===taskId);if(!task)throw new Error('task not found');
  const state=await (await import('./task.js')).readState(task.path),at=new Date();
  const cancellation=await cancelTaskExecution(root,{taskId,round:state.current_round,summary:reason,refs:[`.spec-loop/output/${taskId}-stop.json`],occurredAt:at});
  const cancelledInvocations=[] as string[],incompleteStops=[] as string[];
  for(const item of (await roleInvocations(root)).filter(item=>item.taskId===taskId)){const invocation=await readRoleInvocation(root,item.taskId,item.id).catch(()=>null);if(invocation&&['prepared','running','interrupted','cancelled'].includes(invocation.status))try{await cancelRoleInvocation(root,item.taskId,item.id);cancelledInvocations.push(item.id)}catch(error){incompleteStops.push(`${item.id}:${(error as Error).message}`)}}
  const cancelledEffects=await cancelActiveEffects(root,taskId);incompleteStops.push(...cancelledEffects.incomplete);
  let actualHead:string|null=null;try{const workspace=await readWorkspace(root,taskId);actualHead=(await exec('git',['rev-parse','HEAD'],{cwd:workspace.worktree,maxBuffer:1_000_000,timeout:30_000,killSignal:'SIGKILL'})).stdout.trim()}catch{}
  let acceptanceStage:string|null=null;try{acceptanceStage=(await cancelAcceptanceRun(root,taskId,reason,actualHead)).stage}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT'&&!/ENOENT|completed Candidate/.test((error as Error).message))throw error}
  const finalState=state.status==='cancelled'||state.status==='delivered'||state.status==='draft'?state:await cancelTask(task.path,at);
  const driver=await stopOrReclaimDriverLock(root,taskId,reason,at);
  if(!driver.stop_verified)incompleteStops.push(`driver:${driver.stop_error??'not verified'}`);
  await lock(root,async()=>{for(const lease of await listLeases(taskDir(root),taskLeaseSchema))if(active(lease)&&lease.task_id===taskId)await writeTaskLease(root,taskLeaseSchema.parse({...lease,status:'killed',updated_at:at.toISOString()}))});
  const result={schema_version:2,task_id:taskId,status:finalState.status,acceptance_stage:acceptanceStage,actual_head:actualHead,cancelled_invocations:cancelledInvocations.sort(),cancelled_effects:cancelledEffects.cancelled,incomplete_stops:incompleteStops.sort(),stop_complete:incompleteStops.length===0,closed_steps:cancellation.closed.length,cancellation_event_id:cancellation.cancellation.event_id,driver_lock_reclaimed:driver.reclaimed,driver_stop_requested:driver.stop_requested,driver_stop_verified:driver.stop_verified,driver_stop_error:driver.stop_error,stopped_at:at.toISOString(),reason};
  await atomicWriteMany(root,[{file:marker,content:`${JSON.stringify(result,null,2)}\n`}]);return result;
}
export async function killSchedulerControl(root:string){await initSchedulerControl(root);const current=await state(root),now=new Date().toISOString(),updated=controlStateSchema.parse({...current,paused:true,killed:true,reconcile_required:true,updated_at:now});await writeState(root,updated);const taskIds=new Set<string>((await roleInvocations(root)).map(item=>item.taskId));for(const lease of await listLeases(taskDir(root),taskLeaseSchema))if(active(lease))taskIds.add(lease.task_id);for(const taskId of taskIds)await stopTaskExecution(root,taskId,'scheduler Kill requested').catch(()=>{});await lock(root,async()=>{for(const lease of await listLeases(taskDir(root),taskLeaseSchema))if(active(lease))await writeTaskLease(root,taskLeaseSchema.parse({...lease,status:'killed',updated_at:now}));for(const lease of await listLeases(projectDir(root),projectLeaseSchema))if(active(lease))await writeProjectLease(root,projectLeaseSchema.parse({...lease,status:'killed',updated_at:now}))});return updated}
export async function reconcileSchedulerControl(root:string){for(const item of await roleInvocations(root))await reconcileRoleInvocation(root,item.taskId,item.id).catch(()=>{});const running=[];for(const item of await roleInvocations(root)){const invocation=await readRoleInvocation(root,item.taskId,item.id).catch(()=>null);if(invocation?.status==='running')running.push(invocation.invocation_id)}if(running.length)throw new Error(`role invocations are still running: ${running.join(', ')}`);const current=await state(root),updated=controlStateSchema.parse({...current,killed:false,reconcile_required:false,updated_at:new Date().toISOString()});await writeState(root,updated);return updated}
const stageRole={m_working:'M',plan_compiled:'V',v_passed:'R'} as const;
export async function planReadyWave(root:string){
  const controlState=await state(root),budget=await readWaveBudget(root),schedule=await buildAcceptanceSchedule(root),ready=[] as Array<{task_id:string;stage:string;role:'M'|'V'|'R';action:'start_m'|'start_v'|'start_r';resource:string}>,held=[] as Array<{task_id:string;reason:string}>,candidateRecovery=[] as Array<Record<string,unknown>>;
  for(const task of schedule.tasks.filter(item=>item.stage==='candidate'))try{candidateRecovery.push(await reconcileCandidateBaseline(root,task.task_id,false))}catch(error){candidateRecovery.push({task_id:task.task_id,status:'unavailable',error:(error as Error).message})}
  for(const task of schedule.tasks.filter(item=>item.ready&&item.action)){
    const role=stageRole[task.stage as keyof typeof stageRole];if(!role)continue;
    const latest=await latestRoleInvocation(root,task.task_id,role),nonterminal=latest&&['prepared','running','succeeded','interrupted'].includes(latest.status);
    if(nonterminal){held.push({task_id:task.task_id,reason:latest.status==='succeeded'?`${role} invocation succeeded and awaits result ingestion`:`${role} invocation is ${latest.status}`});continue}
    ready.push({task_id:task.task_id,stage:task.stage,role,action:task.action as 'start_m'|'start_v'|'start_r',resource:`branch:spec-loop/${task.task_id.toLowerCase()}`});
  }
  return{schema_version:1,mode:'wave_execution',executable:!controlState.paused&&!controlState.killed&&!controlState.reconcile_required,control:controlState,budget,ready,held,candidate_recovery:candidateRecovery,planned_at:new Date().toISOString(),destructive_action_performed:false};
}

export async function runReadyWave(root:string,input:{owner:string}){
  if(input.owner.trim().length<2)throw new Error('wave owner must contain at least two characters');
  const supervisor=await (await import('./scheduler-supervisor.js')).startManagedSchedulerSupervisor(root);
  if(!supervisor.running||!supervisor.healthy)throw new Error(`wave execution requires a healthy independent Supervisor (${supervisor.reason})`);
  await reconcileInterruptedWaves(root,true);
  let plan=await planReadyWave(root);if(!plan.executable)throw new Error('scheduler control does not permit execution');
  for(const recovery of plan.candidate_recovery)if(recovery.status==='baseline_drift'&&typeof recovery.task_id==='string')await reconcileCandidateBaseline(root,recovery.task_id,true);
  if(plan.candidate_recovery.some(item=>item.status==='baseline_drift'))plan=await planReadyWave(root);
  const waveId=`WAVE-${Date.now()}-${randomUUID()}`,startedAt=new Date().toISOString(),recordFile=path.join(waveDir(root),`${waveId}.json`),queue=[...plan.ready],results=[] as Array<Record<string,unknown>>,activeTasks=new Set<string>(),reservations=new Map<string,{tokens:number;cost:number}>(),liveUsage=new Map<string,{tokens:number;cost:number}>(),ledger=[] as Array<Record<string,unknown>>,driverStart=await processStartedAt(process.pid);
  let next=0,fuse:string|null=null,totalTokens=0,totalCost=0,reservedTokens=0,reservedCost=0,unknownUsage=false,projectLease:ProjectLease|null=null,stopPromise:Promise<unknown>|null=null,writeTail=Promise.resolve();
  const observed=()=>({tokens:totalTokens+[...liveUsage.values()].reduce((sum,item)=>sum+item.tokens,0),cost:totalCost+[...liveUsage.values()].reduce((sum,item)=>sum+item.cost,0)});
  const persist=async(status:string,finishedAt:string|null)=>{const usage=observed(),snapshot={schema_version:2,wave_id:waveId,status,owner:input.owner,driver:{pid:process.pid,process_started_at:driverStart},supervisor:{pid:supervisor.marker?.pid??null,process_started_at:supervisor.marker?.process_started_at??null},started_at:startedAt,heartbeat_at:new Date().toISOString(),finished_at:finishedAt,budget:plan.budget,planned_tasks:plan.ready.map(item=>item.task_id),pending_tasks:queue.slice(next).map(item=>item.task_id),active_tasks:[...activeTasks].sort(),results,usage:{total_tokens:usage.tokens,cost_usd:usage.cost,recorded:!unknownUsage},reserved:{tokens:reservedTokens,cost_usd:reservedCost},reservations:Object.fromEntries([...reservations].sort()),budget_ledger:ledger.slice(-1000),fuse_reason:fuse};writeTail=writeTail.catch(()=>{}).then(()=>atomicWriteMany(root,[{file:recordFile,content:`${JSON.stringify(snapshot,null,2)}\n`}])).then(()=>{});await writeTail};
  const trip=(reason:string)=>{if(fuse)return;fuse=reason;ledger.push({event:'fuse',reason,at:new Date().toISOString()});stopPromise=Promise.allSettled([...activeTasks].map(taskId=>stopTaskExecution(root,taskId,`wave ${waveId} stopped: ${reason}`)));void persist('stopping',null)};
  await persist('running',null);
  const pulse=setInterval(()=>{void persist(fuse?'stopping':'running',null)},2_000);
  try{
    projectLease=await acquireProjectLease(root,{owner:input.owner,idempotencyKey:waveId,ttlSeconds:plan.budget.max_elapsed_seconds});
    const timer=setTimeout(()=>trip(`elapsed budget reached (${plan.budget.max_elapsed_seconds}s)`),plan.budget.max_elapsed_seconds*1000);
    try{
      const worker=async()=>{for(;;){if(fuse)return;const index=next++;if(index>=queue.length)return;const item=queue[index];let lease:TaskLease|null=null;activeTasks.add(item.task_id);try{
        lease=await acquireTaskLease(root,{projectLeaseId:projectLease!.lease_id,projectFencingToken:projectLease!.fencing_token,taskId:item.task_id,owner:input.owner,idempotencyKey:`${waveId}:${item.task_id}:${item.action}`,ttlSeconds:plan.budget.max_elapsed_seconds,resources:[item.resource],action:item.action});
        const slots=Math.max(1,plan.budget.max_parallel-reservations.size),availableTokens=plan.budget.max_tokens-totalTokens-reservedTokens,availableCost=plan.budget.max_cost_usd-totalCost-reservedCost;if(availableTokens<1||availableCost<=0){trip('wave budget has no reservable capacity');return}const tokenReservation=Math.max(1,Math.floor(availableTokens/slots)),costReservation=availableCost/slots;reservations.set(item.task_id,{tokens:tokenReservation,cost:costReservation});reservedTokens+=tokenReservation;reservedCost+=costReservation;ledger.push({event:'reserve',task_id:item.task_id,tokens:tokenReservation,cost_usd:costReservation,at:new Date().toISOString()});await persist('running',null);
        const invocation=await prepareRoleInvocation(root,item.task_id,item.role),completed=await runRoleInvocation(root,item.task_id,invocation.invocation_id,{maxTokens:tokenReservation,maxCostUsd:costReservation,onUsage:(usage)=>{liveUsage.set(item.task_id,{tokens:usage.total_tokens??0,cost:usage.cost_usd??0});const current=observed();if(current.tokens>=plan.budget.max_tokens)return`wave live token budget reached (${current.tokens}/${plan.budget.max_tokens})`;if(current.cost>=plan.budget.max_cost_usd)return`wave live cost budget reached (${current.cost}/${plan.budget.max_cost_usd})`;return null}});
        if(completed.status==='succeeded')await assertTaskLeaseResult(root,lease.lease_id,lease.fencing_token,completed.invocation_id);
        const ingested=completed.status==='succeeded'?await ingestSucceededRoleResult(root,item.task_id,completed.invocation_id):completed,usage=ingested.usage;liveUsage.delete(item.task_id);totalTokens+=usage.total_tokens??0;totalCost+=usage.cost_usd??0;if(!usage.recorded||usage.cost_usd===null)unknownUsage=true;
        results.push({task_id:item.task_id,role:item.role,invocation_id:ingested.invocation_id,status:ingested.status,result_status:ingested.result_status,result_error:ingested.result_error,usage,reservation:{tokens:tokenReservation,cost_usd:costReservation},next_action:ingested.status==='succeeded'?(ingested.result_status==='ingested'?`${item.role} result ingested and workflow advanced`:`${item.role} result awaits valid Evidence/RESULT.json`):'inspect invocation failure'});activeTasks.delete(item.task_id);ledger.push({event:'settle',task_id:item.task_id,total_tokens:usage.total_tokens,cost_usd:usage.cost_usd,at:new Date().toISOString()});await persist('running',null);
        if(unknownUsage)trip('Provider usage or cost is unrecorded; wave budget cannot be proven');
        else if(totalTokens>=plan.budget.max_tokens)trip(`token budget reached (${totalTokens}/${plan.budget.max_tokens})`);
        else if(totalCost>=plan.budget.max_cost_usd)trip(`cost budget reached (${totalCost}/${plan.budget.max_cost_usd})`);
      }catch(error){results.push({task_id:item.task_id,role:item.role,status:'failed_to_dispatch',error:(error as Error).message});ledger.push({event:'dispatch_failed',task_id:item.task_id,error:(error as Error).message.slice(0,500),at:new Date().toISOString()});}finally{liveUsage.delete(item.task_id);const reservation=reservations.get(item.task_id);if(reservation){reservedTokens-=reservation.tokens;reservedCost-=reservation.cost;reservations.delete(item.task_id)}activeTasks.delete(item.task_id);if(lease)await releaseTaskLease(root,lease.lease_id,lease.fencing_token).catch(()=>{});await persist(fuse?'stopping':'running',null)}}};
      await Promise.all(Array.from({length:Math.min(plan.budget.max_parallel,queue.length)},()=>worker()));
    }finally{clearTimeout(timer);if(stopPromise)await stopPromise}
  }finally{clearInterval(pulse);if(projectLease)await releaseProjectLease(root,projectLease.lease_id,projectLease.fencing_token).catch(()=>{})}
  const status=fuse?(unknownUsage?'usage_unknown':'budget_stopped'):results.some(item=>item.status!=='succeeded'||item.result_status==='invalid')?'completed_with_failures':'completed';await persist(status,new Date().toISOString());return JSON.parse(await readFile(recordFile,'utf8'));
}

export async function reconcileInterruptedWaves(root:string,apply=false){
  await initSchedulerControl(root);const now=Date.now(),items=[] as Array<Record<string,unknown>>;
  for(const name of (await readdir(waveDir(root))).filter(value=>value.endsWith('.json')).sort()){
    const file=path.join(waveDir(root),name),value=JSON.parse(await readFile(file,'utf8')) as Record<string,any>;if(value.status!=='running'&&value.status!=='stopping')continue;
    const heartbeatAge=typeof value.heartbeat_at==='string'?Math.max(0,now-Date.parse(value.heartbeat_at)):null,driver=value.driver as {pid?:number;process_started_at?:string|null}|undefined,driverAlive=await processMatches(driver?.pid,driver?.process_started_at),stale=heartbeatAge===null||heartbeatAge>10_000;
    if(driverAlive&&!stale){items.push({wave_id:value.wave_id,status:'active',heartbeat_age_ms:heartbeatAge,action:'none'});continue}
    const planned=Array.isArray(value.planned_tasks)?value.planned_tasks.filter((item:unknown):item is string=>typeof item==='string'):[],reconciled:string[]=[];
    if(apply){for(const taskId of planned){for(const item of (await roleInvocations(root)).filter(item=>item.taskId===taskId)){let invocation=await readRoleInvocation(root,taskId,item.id).catch(()=>null);if(!invocation)continue;if(invocation.status==='running'){invocation=await reconcileRoleInvocation(root,taskId,item.id);if(invocation.status==='running')invocation=await cancelRoleInvocation(root,taskId,item.id)}if(invocation.status==='prepared'||invocation.status==='interrupted')invocation=await cancelRoleInvocation(root,taskId,item.id);if(invocation.status==='succeeded'&&invocation.result_status!=='ingested')await ingestSucceededRoleResult(root,taskId,item.id);reconciled.push(item.id)}}const plan=await planReadyWave(root),requeued=plan.ready.filter(item=>planned.includes(item.task_id)).map(item=>item.task_id);const updated={...value,schema_version:2,status:'interrupted_requeued',finished_at:new Date().toISOString(),heartbeat_at:new Date().toISOString(),recovery:{reason:driverAlive?'stale_wave_heartbeat':'dead_wave_driver',reconciled_invocations:[...new Set(reconciled)].sort(),requeued_tasks:[...new Set(requeued)].sort(),recovered_at:new Date().toISOString()}};await atomicWriteMany(root,[{file,content:`${JSON.stringify(updated,null,2)}\n`}]);items.push({wave_id:value.wave_id,status:'interrupted_requeued',heartbeat_age_ms:heartbeatAge,action:'reconciled',requeued_tasks:requeued})}
    else items.push({wave_id:value.wave_id,status:driverAlive?'stale_heartbeat':'dead_driver',heartbeat_age_ms:heartbeatAge,action:'inspection_only'});
  }
  return{schema_version:1,apply,reconciled_at:new Date().toISOString(),waves:items};
}

export async function inspectSchedulerLiveness(root:string,staleSeconds=15){
  if(!Number.isInteger(staleSeconds)||staleSeconds<3||staleSeconds>3600)throw new Error('stale heartbeat threshold must be 3–3600 seconds');await initSchedulerControl(root);const now=Date.now(),invocations=[] as Array<Record<string,unknown>>,effects=[] as Array<Record<string,unknown>>,drivers=[] as Array<Record<string,unknown>>,waves=[] as Array<Record<string,unknown>>;
  for(const item of await roleInvocations(root)){const invocation=await readRoleInvocation(root,item.taskId,item.id).catch(()=>null);if(invocation?.status!=='running')continue;const heartbeat=await readFile(path.join(root,'.spec-loop','output',`${item.taskId}-acceptance-v2`,'invocations',item.id,'HEARTBEAT.json'),'utf8').then(raw=>JSON.parse(raw) as {heartbeat_at?:string;last_progress_at?:string;idle_timeout_seconds?:number;process_started_at?:string|null;progress_sequence?:number;output_bytes?:number}).catch(()=>null),heartbeatAt=heartbeat?.heartbeat_at??invocation.heartbeat_at??invocation.started_at,lastProgressAt=heartbeat?.last_progress_at??invocation.last_progress_at??invocation.started_at,age=heartbeatAt?Math.max(0,now-Date.parse(heartbeatAt)):null,progressAge=lastProgressAt?Math.max(0,now-Date.parse(lastProgressAt)):null,idleMs=(heartbeat?.idle_timeout_seconds??300)*1000,alive=await processMatches(invocation.pid,heartbeat?.process_started_at??invocation.process_started_at),status=!alive?'dead_or_pid_reused':age===null?'heartbeat_missing':age>staleSeconds*1000?'controller_stalled':progressAge===null?'progress_missing':progressAge>idleMs?'no_progress':'healthy';invocations.push({task_id:item.taskId,invocation_id:item.id,pid:invocation.pid,heartbeat_at:heartbeatAt,heartbeat_age_ms:age,last_progress_at:lastProgressAt,progress_age_ms:progressAge,idle_timeout_ms:idleMs,progress_sequence:heartbeat?.progress_sequence??invocation.progress_sequence,output_bytes:heartbeat?.output_bytes??null,status})}
  const effectRoot=path.join(root,'.spec-loop','active-effects');for(const name of (await readdir(effectRoot).catch(()=>[])).filter(value=>value.endsWith('.json'))){const value=JSON.parse(await readFile(path.join(effectRoot,name),'utf8')) as {task_id?:string;effect_id?:string;pid?:number;process_started_at?:string|null;heartbeat_at?:string;last_progress_at?:string;started_at?:string;idle_timeout_seconds?:number;progress_sequence?:number;output_bytes?:number},at=value.heartbeat_at??value.started_at??null,progressAt=value.last_progress_at??value.started_at??null,age=at?Math.max(0,now-Date.parse(at)):null,progressAge=progressAt?Math.max(0,now-Date.parse(progressAt)):null,idleMs=(value.idle_timeout_seconds??300)*1000,alive=await processMatches(value.pid,value.process_started_at),status=!alive?'dead_or_pid_reused':age===null?'heartbeat_missing':age>staleSeconds*1000?'controller_stalled':progressAge===null?'progress_missing':progressAge>idleMs?'no_progress':'healthy';effects.push({task_id:value.task_id,effect_id:value.effect_id,pid:value.pid,heartbeat_at:at,heartbeat_age_ms:age,last_progress_at:progressAt,progress_age_ms:progressAge,idle_timeout_ms:idleMs,progress_sequence:value.progress_sequence??null,output_bytes:value.output_bytes??null,status})}
  const locks=path.join(root,'.spec-loop','locks');for(const name of await readdir(locks).catch(()=>[])){const match=name.match(/^workflow-driver-(.+)\.lock$/);if(!match)continue;const owner=await readFile(path.join(locks,name,'owner.json'),'utf8').then(raw=>JSON.parse(raw) as {pid?:number;process_started_at?:string|null;at?:string;created_at?:string}).catch(()=>null),alive=await processMatches(owner?.pid,owner?.process_started_at),status=!alive?'dead_or_pid_reused':owner?.process_started_at?'healthy':'identity_unverified';drivers.push({task_id:match[1],pid:owner?.pid??null,process_started_at:owner?.process_started_at??null,owner_at:owner?.at??owner?.created_at??null,status})}
  for(const name of (await readdir(waveDir(root))).filter(value=>value.endsWith('.json'))){const value=JSON.parse(await readFile(path.join(waveDir(root),name),'utf8')) as {wave_id?:string;status?:string;started_at?:string;heartbeat_at?:string;driver?:{pid?:number;process_started_at?:string|null};budget?:{max_elapsed_seconds?:number};planned_tasks?:string[]};if(value.status!=='running'&&value.status!=='stopping')continue;const age=value.started_at?Math.max(0,now-Date.parse(value.started_at)):null,heartbeatAge=value.heartbeat_at?Math.max(0,now-Date.parse(value.heartbeat_at)):null,limit=(value.budget?.max_elapsed_seconds??0)*1000,driverAlive=await processMatches(value.driver?.pid,value.driver?.process_started_at),waveStatus=!driverAlive?'dead_driver':heartbeatAge===null?'heartbeat_missing':heartbeatAge>Math.max(10_000,staleSeconds*1000)?'stalled':age===null||!limit?'invalid':age>limit+staleSeconds*1000?'overdue':'healthy';waves.push({wave_id:value.wave_id,started_at:value.started_at??null,heartbeat_at:value.heartbeat_at??null,heartbeat_age_ms:heartbeatAge,age_ms:age,max_elapsed_ms:limit,task_ids:value.planned_tasks??[],driver_pid:value.driver?.pid??null,status:waveStatus})}
  const unhealthy=[...invocations,...effects,...drivers,...waves].filter(item=>item.status!=='healthy');return{schema_version:1,checked_at:new Date(now).toISOString(),stale_seconds:staleSeconds,ok:unhealthy.length===0,invocations,effects,drivers,waves,unhealthy};
}
export async function runSchedulerWatchdog(root:string,staleSeconds=15,apply=false){const health=await inspectSchedulerLiveness(root,staleSeconds);if(!apply)return{...health,action:'inspection_only',stopped_tasks:[],wave_recovery:null};const waveRecovery=await reconcileInterruptedWaves(root,true),taskIds=new Set<string>();for(const item of health.unhealthy){if(typeof item.task_id==='string')taskIds.add(item.task_id)}const stopped=[] as Array<Record<string,unknown>>;for(const taskId of [...taskIds].sort())stopped.push(await stopTaskExecution(root,taskId,`watchdog detected stale, dead, or no-progress execution after ${staleSeconds}s`));return{...health,action:'stopped_unhealthy_tasks',stopped_tasks:stopped,wave_recovery:waveRecovery}}

export async function schedulerControlStatus(root:string){return{control:await state(root),budget:await readWaveBudget(root),project_leases:await listLeases(projectDir(root),projectLeaseSchema),task_leases:await listLeases(taskDir(root),taskLeaseSchema)}}
